### ISSUE TITLE
[bug] Returning to Editor After Hitting Button With Bat Crashes Game

### ISSUE THREAD

**Issue by Tzav0002** [caelan-douglas/tinybox#58]
**Version & Platform**
What version and platform did the bug occur on?

Beta 11.1
Windows 10

**Description**
A description of the bug.

After hitting the button block with a bat, pressing return to editor crashes the game instantly.

**Additional info, screenshots, logs**
Any additional info, including screenshots and logs, can be put here.

**Comment by Tzav0002** [comment]
New Find:

This bug applies to buttons as well as half bricks, wheels and seats.

However, the permutation of these blocks matter. There seems to be a common pattern: If the bat hits a surface less than 1 block high, then it will crash the game. For example hitting the front of the seat crashes the game, but the hitting the back does not.

It could be related to hitboxes

**Comment by caelan-douglas** [comment]
Seems to have been fixed in an earlier commit in dev, but is hard to reproduce
